version = 1

[[annotations]]
path = ["data/model*", "data/ram*", "examples/discrete_jacobian.jl"]
SPDX-FileCopyrightText = "2025 Bart van de Lint"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [".github/*", ".gitignore", ".github/workflows/*", "data/*", "docs/src/*", "docs/src/symbolic_awe_model/*"]
SPDX-FileCopyrightText = "2025 Uwe Fechner, Bart van de Lint"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = ["docs/.gitignore", "docs/Project.toml", "Manifest*", "Project*", "CITATION.cff"]
SPDX-FileCopyrightText = "2025 Uwe Fechner, Bart van de Lint"
SPDX-License-Identifier = "MPL-2.0"
