# KPS4 flat-plate kite model using SymbolicAWEModels
#
# Replicates KiteModels.jl's KPS4 model:
# - 4 kite particles (KCU, nose, right tip, left tip)
# - 6-segment main tether
# - 9 bridle springs
# - Flat-plate CL/CD aerodynamics
#
# Uses the same system.yaml settings as KiteModels.jl.

using Pkg
if Base.active_project() != joinpath(@__DIR__, "Project.toml")
    Pkg.activate(@__DIR__)
end

using SymbolicAWEModels
using KiteUtils
using LinearAlgebra

pkg_root = dirname(@__DIR__)
set_data_path(joinpath(pkg_root, "data", "kps4"))
set = deepcopy(load_settings("system.yaml"))

# KPS4 constants
PRE_STRESS = 0.9975
KITE_ANGLE = 4.0  # degrees

# ==================== GEOMETRY ============================ #
# Particle positions from KiteUtils.get_particles
# Points: ground, tether1..6, kcu, nose(A), top(B), right(C),
#         left(D)
# KPS4 mapping: p7=KCU, p8=A(nose), p9=B(top),
#               p10=C(right), p11=D(left)

# Compute initial kite geometry using KiteUtils
particles = KiteUtils.get_particles(
    set.height_k, set.h_bridle, set.width, set.m_k)
# particles = [origin, kcu, nose(A), top(B), right(C), left(D)]
pos_kcu = particles[2]
pos_nose = particles[3]
pos_top = particles[4]
pos_right = particles[5]
pos_left = particles[6]

# ==================== POINTS ============================== #
# Mass distribution from KPS4.init_masses!
kite_mass = set.mass
k_nose = set.rel_nose_mass * kite_mass
k_top = set.rel_top_mass * (1.0 - set.rel_nose_mass) * kite_mass
k_side = 0.5 * (1.0 - set.rel_top_mass) *
         (1.0 - set.rel_nose_mass) * kite_mass
set.mass = 0.0  # masses set explicitly on points

points = Point[]
# Ground point
push!(points, Point(:ground, zeros(3), STATIC))
# Tether points are auto-generated by Route 2 Tether
# KCU
push!(points, Point(:kcu, pos_kcu, DYNAMIC;
    extra_mass=set.kcu_mass))
# Nose (A) — DYNAMIC, gets pitch damping but no plate surface
push!(points, Point(:nose, pos_nose, DYNAMIC;
    extra_mass=k_nose))
# Top (B) — WING point on plate wing
push!(points, Point(:top, pos_top, WING;
    extra_mass=k_top, wing=:plate_wing))
# Right (C) — WING point on plate wing
push!(points, Point(:right, pos_right, WING;
    extra_mass=k_side, wing=:plate_wing))
# Left (D) — WING point on plate wing
push!(points, Point(:left, pos_left, WING;
    extra_mass=k_side, wing=:plate_wing))

# ==================== SEGMENTS ============================ #
# Tether segments (auto-generated by Tether Route 2 below)

# Bridle segments — l0 from initial point distances
pos_map = Dict(:kcu => pos_kcu, :nose => pos_nose,
               :top => pos_top, :right => pos_right,
               :left => pos_left)
bridle_l0(a, b) = norm(pos_map[b] - pos_map[a]) * PRE_STRESS

segments = [
    Segment(:kcu_nose,   set, :kcu,   :nose;
        l0=bridle_l0(:kcu, :nose), diameter_mm=set.d_line),
    Segment(:right_nose, set, :right, :nose;
        l0=bridle_l0(:right, :nose), diameter_mm=set.d_line),
    Segment(:right_left, set, :right, :left;
        l0=bridle_l0(:right, :left), diameter_mm=set.d_line),
    Segment(:top_right,  set, :top,   :right;
        l0=bridle_l0(:top, :right), diameter_mm=set.d_line),
    Segment(:left_kcu,   set, :left,  :kcu;
        l0=bridle_l0(:left, :kcu), diameter_mm=set.d_line),
    Segment(:right_kcu,  set, :right, :kcu;
        l0=bridle_l0(:right, :kcu), diameter_mm=set.d_line),
    Segment(:top_left,   set, :top,   :left;
        l0=bridle_l0(:top, :left), diameter_mm=set.d_line),
    Segment(:left_nose,  set, :left,  :nose;
        l0=bridle_l0(:left, :nose), diameter_mm=set.d_line),
    Segment(:nose_top,   set, :nose,  :top;
        l0=bridle_l0(:nose, :top), diameter_mm=set.d_line),
]

# ==================== TETHER ============================== #
# Route 2: auto-generates tether points and segments
tethers = [Tether(:main_tether, set.l_tethers[1];
    start_point=:ground, end_point=:kcu,
    n_segments=set.segments)]

# ==================== WINCH =============================== #
winches = [Winch(:winch, set, [:main_tether];
                 winch_point=:ground)]

# ==================== PLATE SURFACES ====================== #
# Kite reference frame (computed at initial position):
# z = -normalize(B - midpoint(C,D))  (up from center to nose)
# y = normalize(C - D)               (left to right)
# x = y × z                          (chord direction)
pos_centre = 0.5 * (pos_right + pos_left)
z_kite = -normalize(pos_top - pos_centre)
y_kite = normalize(pos_right - pos_left)
x_kite = y_kite × z_kite

rel_side_area = set.rel_side_area / 100.0

surfaces = [
    # Main surface on particle B (top)
    PlateSurface(:main, x_kite, y_kite,
        set.area * (1.0 - rel_side_area), :top;
        twist_b=-1.0,  # depower reduces AoA
        alpha_offset=set.alpha_zero),
    # Right tip surface on particle C
    PlateSurface(:right_tip, x_kite, z_kite,
        set.area * rel_side_area / 2, :right;
        twist_a=1.0,  # steering increases AoA on right
        alpha_offset=set.alpha_ztip),
    # Left tip surface on particle D
    PlateSurface(:left_tip, x_kite, -z_kite,
        set.area * rel_side_area / 2, :left;
        twist_a=-1.0,  # steering decreases AoA on left
        alpha_offset=set.alpha_ztip),
]

# ==================== CL/CD INTERPOLATIONS ================ #
cl_interp, cd_interp = create_plate_interpolations(
    set.alpha_cl, set.cl_list, set.cd_list;
    alpha_cd=set.alpha_cd)

# ==================== PLATE WING ========================== #
wing = PlateWing(:plate_wing, surfaces, cl_interp, cd_interp;
    wing_type=REFINE,
    z_ref_points=(:top, [:right, :left]),
    y_ref_points=(:left, :right),
    origin=:top,
    drag_corr=0.93,
    cmq=set.cmq,
    smc=set.smc,
    cord_length=set.cord_length)

# ==================== SYSTEM STRUCTURE ==================== #
# No transforms needed — point positions are already in world
# frame from get_particles.
sys = SystemStructure("kps4", set;
    points, segments, tethers, winches,
    wings=[wing])

# ==================== MODEL + SIMULATE ==================== #
sam = SymbolicAWEModel(set, sys)
init!(sam; prn=true)

println("KPS4 PlateWing model initialized.")
println("Points: $(length(sys.points))")
println("Segments: $(length(sys.segments))")
println("Surfaces: $(length(wing.surfaces))")

# Run a short parking simulation
dt = 0.05
n_steps = 200
for i in 1:n_steps
    next_step!(sam; dt, set_values=[0.0])
end
println("Simulated $(n_steps * dt) seconds.")
println("Kite height: $(round(sam.sys_struct.points[:top].pos_w[3], digits=2)) m")
