name: Update xz files

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  update-and-pr:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.pull_request && github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      
    strategy:
      matrix:
        julia-version: ['1.10', '1.11']
        
    steps:
      - name: Install matplotlib
        run: sudo apt-get install -y python3-matplotlib
        shell: bash

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Use default manifest
        run: |
          if [ -f Manifest.toml.default ]; then cp Manifest.toml.default Manifest.toml; fi
        shell: bash

      - name: Set up Julia
        uses: julia-actions/install-juliaup@v2
        with:
          channel: ${{ matrix.julia-version }}
          
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1

      - name: Build PyCall
        run: julia --project -e 'ENV["PYTHON"]=""; using Pkg; Pkg.instantiate(); Pkg.add("PyCall"); Pkg.build("PyCall")'
        shell: bash

      - name: Run update script
        run: bin/update_manifest --default

      - name: Create xz files
        run: bin/create_xz_file

      - name: Remove PyCall
        run: julia --project -e 'ENV["PYTHON"]=""; using Pkg; Pkg.instantiate(); Pkg.rm("PyCall")'
        shell: bash

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: update-manifest-${{ github.run_id }}
          base: main
          title: "Update xz files"
          body: "Automated update of default manifest and xz files."
          commit-message: "Update xz files"

      - name: Trigger CI workflow via repository_dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: auto-pr-created
          client-payload: '{"ref": "refs/heads/update-manifest-${{ github.run_id }}"}'
